import { StyleSheet } from 'react-native';
import { colors as c } from '../theme';
export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: c.cream }, app: { flex: 1, width: '100%', maxWidth: 520, alignSelf: 'center', backgroundColor: c.cream }, scroll: { padding: 24, gap: 16, paddingBottom: 32 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 }, brand: { flexDirection: 'row', alignItems: 'center', gap: 9 }, brandIcon: { color: c.cream, backgroundColor: c.green, borderRadius: 10, paddingHorizontal: 9, paddingVertical: 3, fontSize: 22, fontWeight: '900' }, brandText: { fontSize: 14, color: c.ink, fontWeight: '900', letterSpacing: 1.2 }, pill: { borderWidth: 1, borderColor: c.line, borderRadius: 20, paddingHorizontal: 10, paddingVertical: 7 }, pillText: { fontSize: 8, fontWeight: '800', letterSpacing: 1, color: c.green },
  eyebrow: { color: c.muted, fontSize: 10, fontWeight: '800', letterSpacing: 1.7 }, heroTitle: { fontSize: 32, lineHeight: 45, fontWeight: '900', color: c.ink, letterSpacing: -1 }, title: { fontSize: 28, fontWeight: '800', color: c.ink, lineHeight: 40 }, body: { fontSize: 14, color: c.muted, lineHeight: 23 }, small: { color: c.muted, fontSize: 12, lineHeight: 20 },
  heroScene: { height: 310, borderRadius: 24, overflow: 'hidden', borderWidth: 1, borderColor: '#e8d2a7' }, threeStats: { flexDirection: 'row', width: '100%', paddingVertical: 5 }, miniStat: { flex: 1, alignItems: 'center', gap: 3 }, statValue: { color: c.green, fontSize: 25, fontWeight: '800', fontVariant: ['tabular-nums'] },
  button: { backgroundColor: c.green, borderRadius: 16, paddingVertical: 16, paddingHorizontal: 14, minHeight: 52, alignItems: 'center', justifyContent: 'center', flexGrow: 1 }, secondary: { backgroundColor: c.pale, borderWidth: 1, borderColor: '#dce0c9' }, buttonText: { color: c.cream, fontWeight: '800', fontSize: 14 }, footer: { fontSize: 10, color: c.muted, lineHeight: 18, textAlign: 'center' }, divider: { height: 1, backgroundColor: c.line, marginVertical: 5 },
  routeWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, routeItem: { width: '31%', flexGrow: 1, gap: 5, paddingVertical: 11, paddingHorizontal: 12, borderRadius: 12, backgroundColor: c.pale }, routeNumber: { color: '#94a080', fontSize: 10, fontWeight: '700' }, routeText: { color: c.green, fontSize: 12, fontWeight: '700' },
  link: { color: c.green, fontSize: 13, fontWeight: '700' }, back: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 4 }, segment: { flexDirection: 'row', gap: 8 }, card: { padding: 18, gap: 14, borderRadius: 22, backgroundColor: c.paper, borderWidth: 1, borderColor: c.line }, badgeText: { fontSize: 11, fontWeight: '700' }, practiceTrack: { flexDirection: 'row', height: 100, gap: 8 }, practiceLane: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: c.cream, borderRadius: 12 },
  progress: { height: 5, backgroundColor: '#e0e4cf', overflow: 'hidden' }, progressFill: { height: '100%', backgroundColor: '#91a65e' }, telemetry: { fontSize: 11, color: c.muted, fontVariant: ['tabular-nums'], textAlign: 'center' }, instruction: { flexDirection: 'row', gap: 14, alignItems: 'center' }, instructionIcon: { width: 43, height: 43, textAlign: 'center', textAlignVertical: 'center', lineHeight: 43, fontSize: 24, backgroundColor: c.pale, borderRadius: 12, color: c.green }, instructionTitle: { fontSize: 14, fontWeight: '700', color: c.ink, marginBottom: 4 }, note: { backgroundColor: '#f4edda', borderRadius: 12, padding: 14 },
  gameHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingTop: 12, paddingBottom: 10 }, stageTitle: { fontSize: 24, color: c.ink, fontWeight: '800' }, pause: { backgroundColor: c.pale, padding: 14, borderRadius: 14 }, hud: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 22, paddingBottom: 14 }, hudText: { color: c.green, fontSize: 22, fontWeight: '800', fontVariant: ['tabular-nums'] }, hudUnit: { color: c.muted, fontSize: 11, fontWeight: '500' },
  sceneCaption: { position: 'absolute', top: 12, alignSelf: 'center', maxWidth: '95%', paddingVertical: 8, paddingHorizontal: 14, backgroundColor: '#fff9ebef', borderRadius: 18 }, captionText: { color: c.green, fontSize: 12, fontWeight: '700', textAlign: 'center' }, gameControls: { padding: 14, gap: 8 }, overlay: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, backgroundColor: '#303b2dbb', alignItems: 'center', justifyContent: 'center', padding: 24 }, modal: { width: '100%', padding: 25, gap: 18, alignItems: 'stretch', backgroundColor: c.cream, borderRadius: 26 }, countdown: { fontSize: 88, fontWeight: '900', color: c.green, textAlign: 'center' }, resultArt: { alignItems: 'center', padding: 20 }, resultDistance: { fontSize: 62, fontWeight: '900', color: c.green, fontVariant: ['tabular-nums'] },
});
